services:
  - type: web
    name: radiophone
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server/server.js
    envVars:
      - key: NODE_ENV
        value: production
